### ISSUE TITLE
TODOs in builtin scripts are not detected

### ISSUE THREAD

**Issue by bonbonmiel** [OrigamiDev-Pete/TODO_Manager#11]
This is because the script is in the tscn file.
It should be possible to do since scripts are easily findable in tscn files: 
![image](https://user-images.githubusercontent.com/71937306/118696791-f090b380-b80e-11eb-8baf-50f496cedff8.png)

**Comment by OrigamiDev-Pete** [comment]
Support for built-in scripts was intentionally omitted because some features of TODO Manager are currently incompatible with built-in scripts. However, I added a setting that allows users to enable built-in script scanning, noting that there are some functions that will not work.
You can find the button to enable it in the settings tab, though for now it will be disabled by default.
![image](https://user-images.githubusercontent.com/55121683/118740277-cbdc2080-b88e-11eb-9ea0-4b71c26c9494.png)
You can find it in the latest [release v1.1.3](https://github.com/OrigamiDev-Pete/TODO_Manager/releases/tag/1.1.3) and it should be on the Godot Asset Library in a few days.

Hopefully that helps!

**Comment by bonbonmiel** [comment]
Thanks!
