### ISSUE TITLE
Can't find in Godot Asset Library

### ISSUE THREAD

**Issue by tobydjones** [OrigamiDev-Pete/TODO_Manager#47]
__Godot version:__4.2.1

When I start Godot and search in the "Asset Library Projects" tab, I can't find "TODO Manager".
I found it in the asset library [online](https://godotengine.org/asset-library/asset/768) and saw it's labelled "3.x"
Does that mean it doesn't work with Godot 4, or can you simply update a setting somewhere for it to be available in the asset library in Godot 4?

**Comment by OrigamiDev-Pete** [comment]
That's interesting that the Godot 3 version is being displayed in the AssetLib because as far as I know it should show plugins that are marked as compatible with your current version. The 3.x version definitely doesn't work for Godot 4; the corresponding version should be 'TODO Manager (Godot 4)'.

I just checked in Godot 4.2.2 and it finds the correct version so perhaps it is a bug in 4.2.1.
If you're still encountering the issue, it is also possible to download the plugin from Github directly and place it in your project's addons directory.
