### ISSUE TITLE
Proposal: Kanban-style Tasks Page

### ISSUE THREAD

**Issue by OrigamiDev-Pete** [OrigamiDev-Pete/TODO_Manager#8]
### Tasks Page
**What is it?**
A Trello-style, card-based tasks page to organise TODOs and other custom tasks.

**What can it do?**

- Automatically add TODOs written in scripts to the Tasks page
- Create custom lists/groups of cards to suit any workflow
- Add custom tags
- Assign people to tasks
- Quickly jump to scripts and line-numbers
- Custom colours

![Tasks Design Page1](https://user-images.githubusercontent.com/55121683/103599115-74c95500-4f58-11eb-85b4-4bec72544445.png)

**Card Blueprint**

![card](https://user-images.githubusercontent.com/55121683/103599604-9d9e1a00-4f59-11eb-8fdf-735cac14ef1a.png)

**This is only in the design phase at the moment so any feedback is welcome**

**Comment by OrigamiDev-Pete** [comment]
@orgrinrt @SIsilicon Your feedback would be great if you have any thoughts :)

**Comment by SIsilicon** [comment]
I love it. Unfortunately, I have nothing else to say. Right now, I think that's just how it should be designed.

**Comment by orgrinrt** [comment]
I think the aesthetics seem great. The todo cards from source are intuitive, I'd say. Though something to think about would be to switch the bold heading text to be the todo content (like one would usually do tasks manually) and then the script and line number on the second row. Problem being, it's hard to tell which cards are which at a glance especially if many of them are from the same file (and so at a quick glance you would see a lot of bold texts with the same script name, but have to take a second look to check the actual content).

Another thing I would consider is to turn the TODO, FIXME etc. prefix to a tag or color in the card and leave it out of the task snippet/description to have more space for actual relevant content and again, hopefully save an extra glance you'd have to take if many of the cards content's start with "TODO" and you are a person who glances at text starting from the leftmost position (i.e you'd see just "TODO"s everywhere as opposed to actual identifiable content snippets).

Just some things to consider, not sure if they are actually beneficial or not though.

> Assign people to tasks

Not entirely sure how this would work. Would there be a project-wide usersystem included or would this be git credentials or something in that vein? Or just simply having a list of names (and avatars for aesthetics/easier first glance?) that can be assigned to the tasks like tags?

I once attempted to make a similar thing for godot (though it didn't automatically scrape the todo items from source, it was just a kanban board) but the problem I faced (due to a bad design choice of having it be shared across people in a team in the repo) was the git noise & footprint it generated. I.e a lot of commits just to keep the board updated for everyone if you're working in a team, which adds noise to the repo history. Potentially a lot of it if your team makes active use of it and has a board like "Doing" etc. To keep it synced between people (for example, to have the "Doing" board actually make sense and broadcast to others that someone is already doing a task) is also a bit of a hassle. One person takes a task and marks it to some list, then another person takes the same task and assigns it to a list (could even be the same list, like "Doing"). When they try to push that change, either of them will get a merge conflict and it's going to be a whole thing and wasted time and effort for everyone involved.

So what I'd consider is something that is separate from the project repo. Which you probably already figured. Not sure if I was just going about it too naively in regards to the syncing and such, but either way it will generate a lot of noise in the history which may be undesirable.

Not sure if you already figured this would be a local thing, but I'd say that might be the only way to make it make sense and remain simple. It won't work as a team thing, but it'd help individuals manage their own tasks better, as well as have a glance at all of the project's todo items.

I'm sure, however, that the syncing problem could be just as easily worked around by not using git and making it use an external database. In the simplest approach all it would really need is the connection string and credentials and then the plugin would take over and just do its thing, but in a database. The syncing would be less of a problem and the history noise would be gone completely. This would also allow for 3rd party clients for the tasks but that's probably getting a bit out of scope here.

These were just my initial thoughts, so not sure if you already had a plan for all this that works. I'm certain my mind is a bit limited in this regard so I might just be thinking about it all wrong. Just thought I might chime in, as I've previously failed to create something similar.

**Comment by OrigamiDev-Pete** [comment]
Those are some useful insights! Especially about the git syncing issues that you came up against previously. I'll be honest, it had crossed my mind but I hadn't thought too deeply about it so I'll have to spend some time considering what would be best. Otherwise, keeping it as a 'personal tasks' page would still be useful I think.

**Comment by orgrinrt** [comment]
> Especially about the git syncing issues that you came up against previously

I'd like to emphasis, however, that it could work if implemented better. Not sure how exactly, but it could be that I'm just not experienced enough to think of a good way to implement it. You'd probably have to do some gymnastics with the git porcelain to auto-solve merge conflicts without user intervention and such, but the problem of all those syncs being in the history still exists.

> Otherwise, keeping it as a 'personal tasks' page would still be useful I think

I agree. It might just be that making this local would make most sense. Though I feel like the team aspect would probably be what users would initially expect from a feature like this.

One thing to consider would be to integrate with an existing kanban-like system in the way of providing an interface to do basic things with it as well as automatically import the source todos from the plugin to the board.

Github has some sort of api access to their projects (https://docs.github.com/en/free-pro-team@latest/rest/reference/projects) though I'm not sure how it authenticates or works. From a quick glance it seems that the project api provides access to most things the integration would need (create card, delete card, move card etc.). There's .NET flavor of [octokit](https://docs.github.com/en/free-pro-team@latest/rest/overview/libraries) that could potentially be used but it'd probably be easiest to just use the http api directly.

Gitlab also has an api for its issues and boards but not sure if it needs extra configuration on self-hosted instances. https://docs.gitlab.com/ee/api/issues.html. From a glance it looks like it has most things you'd need too.

Wekan, which is one self-hosted open source alternative to trello, has an api as well https://wekan.github.io/api/v4.70/#wekan-rest-api. I would assume that most open source alternatives do, but it'd mean that the user has to have an instance running or that they have to roll one to get the kanban functionality.

Then there's trello of course, but I won't spend time looking at that one. https://developer.atlassian.com/cloud/trello/guides/rest-api/api-introduction/

Using a pre-existing system would certainly be easier, but a lot more boring to write the client. Also it could just be out of scope to do something like this, though writing own kanban implementation is not a trivial undertaking itself.

Obviously this'd have some limitations like needing an internet connection (versus a fully local board) but it'd also offer the ease of just implementing a simplistic client for existing kanban system without needing to invent the wheel again, as well as allowing for working as a team with the board without needing to do a complex(?) stuff with git.

Now, I don't know how efficient it would be to use a http api for something like this, but there already are some projects that make use of these apis for a very similar purpose (like https://kanban.leanlabs.io/). From the way I've used kanban boards, there isn't very frequent or rapid changes so I would assume it'd be okay.

**Comment by OrigamiDev-Pete** [comment]
A lot of food for thought here. Thanks for having a look around for some options, I really appreciate it! I'm going to try implementing some of the basic UI (cards, lists) soon and I'm still trying to work out the the nuts and bolts of how the TODO's will keep track of the cards so that they don't keep on duplicating themselves seeing as right now the TODO list can completely delete and rebuild itself fairly regularly, so I'm probably going to need to rethink how the list updates before I dive too deep.
